name: CI-tests
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      #checkout repo
      - name: Check out repository code
        uses: actions/checkout@v3
      #Install Node.js
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"

      # Install package dependencies as defined in package.json file in root of project.
      - name: install
        run: npm install
      # Run `gatsby build`.
      - name: build
        run: npm run build
